### ISSUE TITLE
Absurdly slow

### ISSUE THREAD

**Issue by rewong03** [xtracthub/xtract-keyword#1]
pub8\CdiacBundles\35MJ\metadata_coli12mar24mar2015.doc <- 770 seconds
pub8\CdiacBundles\35MJ\metadata_coli26feb10mar2015.doc <- 633 seconds
pub8\CdiacBundles\35MJ\metadata_coli26may4jun2015.doc <- 620 seconds
pub8\CdiacBundles\35MJ\metadata_coli7jun18jun2015.doc <- 619 seconds

**Comment by tskluzac** [comment]
@rewong03 is it any faster now that we added Rake?

**Comment by rewong03** [comment]
Solved now that we're using rake.
pub8\CdiacBundles\35MJ\metadata_coli12mar24mar2015.doc <- 325
pub8\CdiacBundles\35MJ\metadata_coli26feb10mar2015.doc <- 334
pub8\CdiacBundles\35MJ\metadata_coli26may4jun2015.doc <- 328
pub8\CdiacBundles\35MJ\metadata_coli7jun18jun2015.doc <- 324
